[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.140.7",
    "matplotlib>=3.10.9",
    "opencv-python>=5.0.0.93",
    "pandas>=2.3.3",
    "pydantic>=2.13.4",
    "tqdm>=4.70.0",
]

[dependency-groups]
dev = [
    "pylint>=4.0.6",
]

[tool.pylint."messages control"]
disable = [
    "E1101",
    "C0103",
    "C0200",
    "C0301",
]